### ISSUE TITLE
buff 解析错误信息： null

### ISSUE THREAD

**Issue by SXZXD** [lmxdawn/him-vue#1]
你好，登陆校验报这个错，是什么原因导致呢

**Comment by lmxdawn** [comment]
麻烦截个图，是我线上部署的，还是你本地运行的

**Comment by SXZXD** [comment]
线上本地都会报这个错
  
 



------------------ 原始邮件 ------------------
发件人: "兰茗翔"<notifications@github.com>; 
发送时间: 2019年7月8日(星期一) 下午2:59
收件人: "lmxdawn/him-vue"<him-vue@noreply.github.com>; 
抄送: "丿保存丶"<635310636@QQ.COM>; "Author"<author@noreply.github.com>; 
主题: Re: [lmxdawn/him-vue] buff 解析错误信息： null (#1)




麻烦截个图，是我线上部署的，还是你本地运行的

**Comment by lmxdawn** [comment]
嗯嗯，这个不是错，buff 解析错误：null
错误信息是 null ，说明没有错误

**Comment by SXZXD** [comment]
嗯嗯，谢谢，！我还是第一次用这个解析，有点懵，有没有相关的资源，资料，分享一下 ，我学习学习！
 



------------------ 原始邮件 ------------------
发件人: "兰茗翔"<notifications@github.com>; 
发送时间: 2019年7月8日(星期一) 下午3:10
收件人: "lmxdawn/him-vue"<him-vue@noreply.github.com>; 
抄送: "丿保存丶"<635310636@QQ.COM>; "Author"<author@noreply.github.com>; 
主题: Re: [lmxdawn/him-vue] buff 解析错误信息： null (#1)




嗯嗯，这个不是错，buff 解析错误：null
 错误信息是 null ，说明没有错误

**Comment by lmxdawn** [comment]
https://juejin.im/post/5bcda388e51d457a1179da01
