### ISSUE TITLE
netty对应多个Protobuf怎么处理

### ISSUE THREAD

**Issue by sunmingji** [lmxdawn/him-vue#3]
为什么发送消息不用websocket
而是用http
因为需要对应多个Protobuf吗

**Comment by lmxdawn** [comment]
我是为了解耦，这样发消息只用http，更好的扩展，每个服务的功能更单一。比如现在弄一个netty的集群，用http的话就可以更好的分发到不同的集群上面，因为接入集群后给某个用户发消息的话就必须先知道用户在那台服务上，个人觉得这个时候用http更好一些，这样websocket功能就单一了。事实上很多系统发消息都是http，然后接收消息都是socket 长链接或者长轮询。他们是什么原因我就不知道了。另外你问的对应多个Protobuf我没明白。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sunmingji <notifications@github.com&gt;
发送时间: 2019年11月2日 22:03
收件人: lmxdawn/him-vue <him-vue@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[lmxdawn/him-vue] netty对应多个Protobuf怎么处理 (#3)




为什么发送消息不用websocket
 而是用http
 因为需要对应多个Protobuf吗

**Comment by sunmingji** [comment]
多谢解答,
想法是发送消息也使用websocket,登录和心跳的时候已经对应一个protobuf了，
若加入发送消息的protobuf 服务端应该对应多个protobuf的编码了

**Comment by lmxdawn** [comment]
代码里面有多个的嘛，现在就是多个，需要自己定义一个 proto文件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sunmingji <notifications@github.com&gt;
发送时间: 2019年11月4日 14:52
收件人: lmxdawn/him-vue <him-vue@noreply.github.com&gt;
抄送: lmxdawn <lmxdawn@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[lmxdawn/him-vue] netty对应多个Protobuf怎么处理 (#3)




多谢解答,
 想法是发送消息也使用websocket,登录和心跳的时候已经对应一个protobuf了，
 若加入发送消息的protobuf 服务端应该对应多个protobuf的编码了

**Comment by sunmingji** [comment]
嗯嗯 是多个proto文件
但是在WSServerInitializer中ProtobufDecoder需要放入一个实例。这个不可以串行吧，发送过来的消息可能是心跳也有可能是消息
 // 协议包解码时指定Protobuf字节数实例化为CommonProtocol类型
        pipeline.addLast(new ProtobufDecoder(WSBaseReqProtoOuterClass.WSBaseReqProto.getDefaultInstance()));

**Comment by lmxdawn** [comment]
> 
> 
> 嗯嗯 是多个proto文件
> 但是在WSServerInitializer中ProtobufDecoder需要放入一个实例。这个不可以串行吧，发送过来的消息可能是心跳也有可能是消息
> // 协议包解码时指定Protobuf字节数实例化为CommonProtocol类型
> pipeline.addLast(new ProtobufDecoder(WSBaseReqProtoOuterClass.WSBaseReqProto.getDefaultInstance()));

根据类型来呀，不知道你看了源码没有，现在的逻辑就是心跳和登录是分开的 
WSServerHandler  里面的，那个基础的 WSBaseReqProto 肯定不能动，你自己建立一个 proto 文件，继承这个 WSBaseReqProto 基础的就行了，然后接收的时候判断类是哪一个。或者根据里面的 Type 来判断。

```
    /**
     * 读到客户端的内容 （这里只做心跳检查）
     * @param ctx
     * @param msg
     * @throws Exception
     */
    @Override
    protected void channelRead0(ChannelHandlerContext ctx, WSBaseReqProtoOuterClass.WSBaseReqProto msg) throws Exception {

        String sid = msg.getSid();
        long uid = msg.getUid();
        Integer type = msg.getType();
        switch (type) {
            case WSReqTypeConstant.LOGIN: // 登录类型
                log.info("用户登录");
                userLogin(ctx, uid, sid);
                break;
            case WSReqTypeConstant.PING: // 心跳
                log.info("客户端心跳");
                break;
            default:
                log.info("未知类型");
        }

    }
```

**Comment by sunmingji** [comment]
好的 明白了
down下来看一下
